"""add v1 backend models

Revision ID: 4859effd0277
Revises: 12bc9ab0d3dd
Create Date: 2026-08-08 16:35:52.683574

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4859effd0277"
down_revision: str | Sequence[str] | None = "12bc9ab0d3dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_run_records",
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("trace_id", sa.String(length=128), nullable=True),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                name="ai_run_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("model_version", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=128), nullable=True),
        sa.Column("schema_version", sa.String(length=128), nullable=True),
        sa.Column("embedding_version", sa.String(length=128), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("input_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_run_records_is_deleted"), "ai_run_records", ["is_deleted"], unique=False
    )
    op.create_index(
        "ix_ai_run_records_target", "ai_run_records", ["target_type", "target_id"], unique=False
    )
    op.create_index(
        "ix_ai_run_records_trace", "ai_run_records", ["trace_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_ai_run_records_workspace_id"), "ai_run_records", ["workspace_id"], unique=False
    )
    op.create_table(
        "review_records",
        sa.Column("asset_type", sa.String(length=32), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("before_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_review_records_asset", "review_records", ["asset_type", "asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_review_records_is_deleted"), "review_records", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_review_records_workspace_id"), "review_records", ["workspace_id"], unique=False
    )
    op.create_table(
        "expert_contributions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "source_author",
                "asset_contributor",
                "reviewer",
                name="contribution_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("asset_type", sa.String(length=32), nullable=True),
        sa.Column("asset_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "source_id", "role", name="uq_expert_contributions_user_source_role"
        ),
    )
    op.create_index(
        op.f("ix_expert_contributions_is_deleted"),
        "expert_contributions",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        "ix_expert_contributions_source",
        "expert_contributions",
        ["source_id", "updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_expert_contributions_workspace_id"),
        "expert_contributions",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "research_tasks",
        sa.Column("customer_profile_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("completion_conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "planning",
                "researching",
                "waiting_expert",
                "synthesizing",
                "completed",
                "failed",
                "cancelled",
                name="research_task_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("trace_id", sa.String(length=128), nullable=False),
        sa.Column("profile_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("conversation_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("research_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("findings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("routes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("audit", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("knowledge_gaps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expert_questions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("research_document_url", sa.String(length=2000), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_summary", sa.String(length=1000), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("cancel_reason", sa.String(length=1000), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["customer_profile_id"], ["customer_profiles.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_tasks_is_deleted"), "research_tasks", ["is_deleted"], unique=False
    )
    op.create_index(
        "ix_research_tasks_profile_updated",
        "research_tasks",
        ["customer_profile_id", "updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_tasks_workspace_id"), "research_tasks", ["workspace_id"], unique=False
    )
    op.create_index(
        "ix_research_tasks_workspace_status",
        "research_tasks",
        ["workspace_id", "status"],
        unique=False,
    )
    op.create_table(
        "expert_collaborations",
        sa.Column("research_task_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "awaiting_confirmation",
                "group_created",
                "sent",
                "closed",
                "failed",
                name="expert_collaboration_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("group_name", sa.String(length=200), nullable=False),
        sa.Column("candidate_records", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("selected_expert_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("questions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("context_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_bundle", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("feishu_document_id", sa.String(length=256), nullable=True),
        sa.Column("feishu_document_url", sa.String(length=2000), nullable=True),
        sa.Column("feishu_group_id", sa.String(length=256), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_summary", sa.String(length=1000), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["research_task_id"], ["research_tasks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_expert_collaborations_is_deleted"),
        "expert_collaborations",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        "ix_expert_collaborations_task_status",
        "expert_collaborations",
        ["research_task_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_expert_collaborations_workspace_id"),
        "expert_collaborations",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "research_steps",
        sa.Column("research_task_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                name="research_step_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("input_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_summary", sa.String(length=1000), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["research_task_id"], ["research_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("research_task_id", "sequence", name="uq_research_steps_task_sequence"),
    )
    op.create_index(
        op.f("ix_research_steps_is_deleted"), "research_steps", ["is_deleted"], unique=False
    )
    op.create_index(
        "ix_research_steps_task_status",
        "research_steps",
        ["research_task_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_steps_workspace_id"), "research_steps", ["workspace_id"], unique=False
    )
    op.create_table(
        "expert_replies",
        sa.Column("research_task_id", sa.UUID(), nullable=False),
        sa.Column("collaboration_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.String(length=128), nullable=False),
        sa.Column("author_id", sa.String(length=128), nullable=False),
        sa.Column("author_name", sa.String(length=200), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("feishu_message_id", sa.String(length=256), nullable=False),
        sa.Column("message_url", sa.String(length=2000), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "invited",
                "answered",
                "accepted",
                "rejected",
                "closed",
                name="expert_reply_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("adopted_experience_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["adopted_experience_id"], ["experiences.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["collaboration_id"], ["expert_collaborations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["research_task_id"], ["research_tasks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("feishu_message_id", name="uq_expert_replies_message"),
    )
    op.create_index(
        op.f("ix_expert_replies_is_deleted"), "expert_replies", ["is_deleted"], unique=False
    )
    op.create_index(
        "ix_expert_replies_task", "expert_replies", ["research_task_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_expert_replies_workspace_id"), "expert_replies", ["workspace_id"], unique=False
    )
    op.add_column("customer_profiles", sa.Column("confirmed_by_id", sa.UUID(), nullable=True))
    op.add_column(
        "customer_profiles",
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_customer_profiles_confirmed_by_id"),
        "customer_profiles",
        ["confirmed_by_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_customer_profiles_confirmed_by",
        "customer_profiles",
        "users",
        ["confirmed_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("capabilities", sa.Column("reviewed_by_id", sa.UUID(), nullable=True))
    op.add_column(
        "capabilities", sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "capabilities", sa.Column("source_version_at_review", sa.Integer(), nullable=True)
    )
    op.add_column(
        "capabilities",
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    )
    op.add_column("capabilities", sa.Column("embedding_text", sa.Text(), nullable=True))
    op.add_column(
        "capabilities", sa.Column("embedding_version", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "capabilities", sa.Column("embedding_fingerprint", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "capabilities",
        sa.Column("embedding_ready", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.create_index(
        op.f("ix_capabilities_reviewed_by_id"), "capabilities", ["reviewed_by_id"], unique=False
    )
    op.create_foreign_key(
        "fk_capabilities_reviewed_by",
        "capabilities",
        "users",
        ["reviewed_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("experiences", sa.Column("reviewed_by_id", sa.UUID(), nullable=True))
    op.add_column(
        "experiences", sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("experiences", sa.Column("source_version_at_review", sa.Integer(), nullable=True))
    op.add_column(
        "experiences",
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    )
    op.add_column("experiences", sa.Column("embedding_text", sa.Text(), nullable=True))
    op.add_column(
        "experiences", sa.Column("embedding_version", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "experiences", sa.Column("embedding_fingerprint", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "experiences",
        sa.Column("embedding_ready", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.create_index(
        op.f("ix_experiences_reviewed_by_id"), "experiences", ["reviewed_by_id"], unique=False
    )
    op.create_foreign_key(
        "fk_experiences_reviewed_by",
        "experiences",
        "users",
        ["reviewed_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "sources",
        sa.Column(
            "freshness_status",
            sa.Enum(
                "current",
                "updated",
                "permission_denied",
                "deleted",
                name="source_freshness_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="current",
            nullable=False,
        ),
    )
    op.add_column("sources", sa.Column("content_fingerprint", sa.String(length=64), nullable=True))
    op.add_column(
        "sources", sa.Column("content_version", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column(
        "sources", sa.Column("permission_checked_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("sources", sa.Column("previous_version_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_sources_previous_version_id"),
        "sources",
        ["previous_version_id"],
        unique=False,
    )
    op.create_index(
        "uq_expert_collaborations_active_task",
        "expert_collaborations",
        ["workspace_id", "research_task_id"],
        unique=True,
        postgresql_where=sa.text(
            "is_deleted = false AND status IN "
            "('draft', 'awaiting_confirmation', 'group_created', 'sent')"
        ),
    )
    op.create_foreign_key(
        "fk_sources_previous_version",
        "sources",
        "sources",
        ["previous_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("users", sa.Column("feishu_tenant_key", sa.String(length=128), nullable=True))
    op.add_column("users", sa.Column("feishu_access_token", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("feishu_refresh_token", sa.Text(), nullable=True))
    op.add_column(
        "users", sa.Column("feishu_token_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "feishu_token_expires_at")
    op.drop_column("users", "feishu_refresh_token")
    op.drop_column("users", "feishu_access_token")
    op.drop_column("users", "feishu_tenant_key")
    op.drop_constraint("fk_sources_previous_version", "sources", type_="foreignkey")
    op.drop_index(op.f("ix_sources_previous_version_id"), table_name="sources")
    op.drop_column("sources", "previous_version_id")
    op.drop_column("sources", "permission_checked_at")
    op.drop_column("sources", "content_version")
    op.drop_column("sources", "content_fingerprint")
    op.drop_column("sources", "freshness_status")
    op.drop_constraint("fk_experiences_reviewed_by", "experiences", type_="foreignkey")
    op.drop_index(op.f("ix_experiences_reviewed_by_id"), table_name="experiences")
    op.drop_column("experiences", "embedding_ready")
    op.drop_column("experiences", "embedding_fingerprint")
    op.drop_column("experiences", "embedding_version")
    op.drop_column("experiences", "embedding_text")
    op.drop_column("experiences", "embedding")
    op.drop_column("experiences", "source_version_at_review")
    op.drop_column("experiences", "reviewed_at")
    op.drop_column("experiences", "reviewed_by_id")
    op.drop_constraint("fk_capabilities_reviewed_by", "capabilities", type_="foreignkey")
    op.drop_index(op.f("ix_capabilities_reviewed_by_id"), table_name="capabilities")
    op.drop_column("capabilities", "embedding_ready")
    op.drop_column("capabilities", "embedding_fingerprint")
    op.drop_column("capabilities", "embedding_version")
    op.drop_column("capabilities", "embedding_text")
    op.drop_column("capabilities", "embedding")
    op.drop_column("capabilities", "source_version_at_review")
    op.drop_column("capabilities", "reviewed_at")
    op.drop_column("capabilities", "reviewed_by_id")
    op.drop_constraint("fk_customer_profiles_confirmed_by", "customer_profiles", type_="foreignkey")
    op.drop_index(op.f("ix_customer_profiles_confirmed_by_id"), table_name="customer_profiles")
    op.drop_column("customer_profiles", "confirmed_at")
    op.drop_column("customer_profiles", "confirmed_by_id")
    op.drop_index(op.f("ix_expert_replies_workspace_id"), table_name="expert_replies")
    op.drop_index("ix_expert_replies_task", table_name="expert_replies")
    op.drop_index(op.f("ix_expert_replies_is_deleted"), table_name="expert_replies")
    op.drop_table("expert_replies")
    op.drop_index(op.f("ix_research_steps_workspace_id"), table_name="research_steps")
    op.drop_index("ix_research_steps_task_status", table_name="research_steps")
    op.drop_index(op.f("ix_research_steps_is_deleted"), table_name="research_steps")
    op.drop_table("research_steps")
    op.drop_index(op.f("ix_expert_collaborations_workspace_id"), table_name="expert_collaborations")
    op.drop_index("ix_expert_collaborations_task_status", table_name="expert_collaborations")
    op.drop_index(op.f("ix_expert_collaborations_is_deleted"), table_name="expert_collaborations")
    op.drop_table("expert_collaborations")
    op.drop_index("ix_research_tasks_workspace_status", table_name="research_tasks")
    op.drop_index(op.f("ix_research_tasks_workspace_id"), table_name="research_tasks")
    op.drop_index("ix_research_tasks_profile_updated", table_name="research_tasks")
    op.drop_index(op.f("ix_research_tasks_is_deleted"), table_name="research_tasks")
    op.drop_table("research_tasks")
    op.drop_index(op.f("ix_expert_contributions_workspace_id"), table_name="expert_contributions")
    op.drop_index("ix_expert_contributions_source", table_name="expert_contributions")
    op.drop_index(op.f("ix_expert_contributions_is_deleted"), table_name="expert_contributions")
    op.drop_table("expert_contributions")
    op.drop_index(op.f("ix_review_records_workspace_id"), table_name="review_records")
    op.drop_index(op.f("ix_review_records_is_deleted"), table_name="review_records")
    op.drop_index("ix_review_records_asset", table_name="review_records")
    op.drop_table("review_records")
    op.drop_index(op.f("ix_ai_run_records_workspace_id"), table_name="ai_run_records")
    op.drop_index("ix_ai_run_records_trace", table_name="ai_run_records")
    op.drop_index("ix_ai_run_records_target", table_name="ai_run_records")
    op.drop_index(op.f("ix_ai_run_records_is_deleted"), table_name="ai_run_records")
    op.drop_table("ai_run_records")
    # ### end Alembic commands ###
