"""feat: add presentation and html generation models

Revision ID: 509d9268f418
Revises: ad6d677729da
Create Date: 2026-08-10 14:02:35.057139

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "509d9268f418"
down_revision: str | Sequence[str] | None = "ad6d677729da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "narrative_profiles",
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "rules",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_narrative_profiles_is_deleted"), "narrative_profiles", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_narrative_profiles_workspace_id"),
        "narrative_profiles",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_narrative_profiles_workspace_name",
        "narrative_profiles",
        ["workspace_id", "name"],
        unique=False,
    )
    op.add_column(
        "html_artifacts",
        sa.Column("status", sa.String(length=32), server_default="draft", nullable=False),
    )
    op.add_column(
        "html_artifacts",
        sa.Column(
            "upstream_status", sa.String(length=32), server_default="released", nullable=False
        ),
    )
    op.add_column(
        "html_artifacts",
        sa.Column(
            "artifact_paths",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "html_artifacts",
        sa.Column(
            "preview_screenshot_keys",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "html_artifacts", sa.Column("html_object_key", sa.String(length=1000), nullable=True)
    )
    op.add_column(
        "html_artifacts", sa.Column("pdf_object_key", sa.String(length=1000), nullable=True)
    )
    op.add_column("style_profiles", sa.Column("narrative_profile_id", sa.UUID(), nullable=True))
    op.add_column(
        "style_profiles",
        sa.Column(
            "palette",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "style_profiles",
        sa.Column(
            "typography",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "style_profiles",
        sa.Column(
            "layout_grammar",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "style_profiles",
        sa.Column("density", sa.String(length=16), server_default="medium", nullable=False),
    )
    op.add_column(
        "style_profiles",
        sa.Column(
            "shape_language",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "style_profiles",
        sa.Column(
            "logo_rules",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "style_profiles",
        sa.Column(
            "confidence_notes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_style_profiles_narrative_profile_id"),
        "style_profiles",
        ["narrative_profile_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_style_profiles_narrative_profile_id_narrative_profiles",
        "style_profiles",
        "narrative_profiles",
        ["narrative_profile_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_style_profiles_narrative_profile_id_narrative_profiles",
        "style_profiles",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_style_profiles_narrative_profile_id"), table_name="style_profiles")
    op.drop_column("style_profiles", "confidence_notes")
    op.drop_column("style_profiles", "logo_rules")
    op.drop_column("style_profiles", "shape_language")
    op.drop_column("style_profiles", "density")
    op.drop_column("style_profiles", "layout_grammar")
    op.drop_column("style_profiles", "typography")
    op.drop_column("style_profiles", "palette")
    op.drop_column("style_profiles", "narrative_profile_id")
    op.drop_column("html_artifacts", "pdf_object_key")
    op.drop_column("html_artifacts", "html_object_key")
    op.drop_column("html_artifacts", "preview_screenshot_keys")
    op.drop_column("html_artifacts", "artifact_paths")
    op.drop_column("html_artifacts", "upstream_status")
    op.drop_column("html_artifacts", "status")
    op.drop_index("ix_narrative_profiles_workspace_name", table_name="narrative_profiles")
    op.drop_index(op.f("ix_narrative_profiles_workspace_id"), table_name="narrative_profiles")
    op.drop_index(op.f("ix_narrative_profiles_is_deleted"), table_name="narrative_profiles")
    op.drop_table("narrative_profiles")
    # ### end Alembic commands ###
