"""add immutable presentation render snapshots

Revision ID: 712f72264fd8
Revises: a122639db712
Create Date: 2026-08-11 12:16:49.628573

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "712f72264fd8"
down_revision: str | Sequence[str] | None = "a122639db712"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "presentation_render_snapshots",
        sa.Column("presentation_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("fact_ledger_hash", sa.String(length=64), nullable=False),
        sa.Column("positioned_spec_hash", sa.String(length=64), nullable=False),
        sa.Column("compiled_style_hash", sa.String(length=64), nullable=False),
        sa.Column("render_ir_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "fact_ledger_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("render_ir_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("renderer_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "diagnostics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["presentation_id"], ["presentation_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "presentation_id", "version", name="uq_presentation_render_snapshot_version"
        ),
    )
    op.create_index(
        "ix_presentation_render_snapshot_hash",
        "presentation_render_snapshots",
        ["render_ir_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_presentation_render_snapshots_is_deleted"),
        "presentation_render_snapshots",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_presentation_render_snapshots_workspace_id"),
        "presentation_render_snapshots",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_presentation_render_snapshots_workspace_id"),
        table_name="presentation_render_snapshots",
    )
    op.drop_index(
        op.f("ix_presentation_render_snapshots_is_deleted"),
        table_name="presentation_render_snapshots",
    )
    op.drop_index(
        "ix_presentation_render_snapshot_hash", table_name="presentation_render_snapshots"
    )
    op.drop_table("presentation_render_snapshots")
    # ### end Alembic commands ###
