"""add style template versions

Revision ID: a122639db712
Revises: 509d9268f418
Create Date: 2026-08-11 11:31:49.923465

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a122639db712"
down_revision: str | Sequence[str] | None = "509d9268f418"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "style_template_versions",
        sa.Column("style_profile_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "previewing",
                "needs_review",
                "confirmed",
                "rejected",
                "superseded",
                "failed",
                name="style_template_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("archetype_token", sa.String(length=64), nullable=False),
        sa.Column(
            "source_deck_hashes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("feature_set_hash", sa.String(length=64), nullable=False),
        sa.Column("compiled_template_hash", sa.String(length=64), nullable=False),
        sa.Column("compiler_version", sa.String(length=32), nullable=False),
        sa.Column(
            "compiled_template_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("confidence_report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("validation_report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "preview_artifacts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("confirmed_by_id", sa.UUID(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["confirmed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["style_profile_id"], ["style_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "style_profile_id",
            "candidate_id",
            "version",
            name="uq_style_template_profile_candidate_version",
        ),
    )
    op.create_index(
        "ix_style_template_profile_version_status",
        "style_template_versions",
        ["style_profile_id", "version", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_style_template_versions_is_deleted"),
        "style_template_versions",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_style_template_versions_workspace_id"),
        "style_template_versions",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_style_template_versions_workspace_id"), table_name="style_template_versions"
    )
    op.drop_index(
        op.f("ix_style_template_versions_is_deleted"), table_name="style_template_versions"
    )
    op.drop_index("ix_style_template_profile_version_status", table_name="style_template_versions")
    op.drop_table("style_template_versions")
    # ### end Alembic commands ###
