"""add trustworthy orchestration and presentations

Revision ID: ad6d677729da
Revises: 93bc71c26c41
Create Date: 2026-08-09 15:42:39.505950

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad6d677729da"
down_revision: str | Sequence[str] | None = "93bc71c26c41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_tasks",
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "completed",
                "failed",
                "cancelled",
                name="workflow_task_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_summary", sa.String(length=1000), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "target_id", name="uq_workflow_task_kind_target"),
    )
    op.create_index(
        "ix_workflow_tasks_claim",
        "workflow_tasks",
        ["status", "available_at", "lease_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_tasks_is_deleted"), "workflow_tasks", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_tasks_workspace_id"), "workflow_tasks", ["workspace_id"], unique=False
    )
    op.create_table(
        "reference_decks",
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.String(length=256), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column("storage_key", sa.String(length=1000), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "parsing",
                "parsed",
                "profile_draft",
                "profile_confirmed",
                "failed",
                name="reference_deck_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("parse_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("security_report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "file_hash", "version", name="uq_reference_deck_hash_version"
        ),
    )
    op.create_index(
        op.f("ix_reference_decks_is_deleted"), "reference_decks", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_reference_decks_workspace_id"), "reference_decks", ["workspace_id"], unique=False
    )
    op.create_table(
        "style_profiles",
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("reference_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "confirmed",
                name="style_profile_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("visual_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("narrative_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("conflict_notes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confirmed_by_id", sa.UUID(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["confirmed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_style_profiles_is_deleted"), "style_profiles", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_style_profiles_workspace_id"), "style_profiles", ["workspace_id"], unique=False
    )
    op.create_index(
        "ix_style_profiles_workspace_status",
        "style_profiles",
        ["workspace_id", "status"],
        unique=False,
    )
    op.create_table(
        "claim_records",
        sa.Column("solution_run_id", sa.UUID(), nullable=False),
        sa.Column("claim_key", sa.String(length=160), nullable=False),
        sa.Column("section", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("claim_type", sa.String(length=64), nullable=False),
        sa.Column("boundary", sa.String(length=64), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column(
            "verification_status",
            sa.Enum(
                "entailed",
                "contradicted",
                "insufficient",
                "invalid",
                name="claim_verification_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("released", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("candidate_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["solution_run_id"], ["solution_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "solution_run_id", "candidate_version", "claim_key", name="uq_claim_records_run_key"
        ),
    )
    op.create_index(
        op.f("ix_claim_records_is_deleted"), "claim_records", ["is_deleted"], unique=False
    )
    op.create_index(
        "ix_claim_records_run_status",
        "claim_records",
        ["solution_run_id", "verification_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_claim_records_workspace_id"), "claim_records", ["workspace_id"], unique=False
    )
    op.create_table(
        "evidence_records",
        sa.Column("solution_run_id", sa.UUID(), nullable=False),
        sa.Column("evidence_key", sa.String(length=256), nullable=False),
        sa.Column("candidate_version", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_version", sa.Integer(), nullable=False),
        sa.Column("reviewed_source_version", sa.Integer(), nullable=True),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("location", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("permission_status", sa.String(length=32), nullable=False),
        sa.Column("permission_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["solution_run_id"], ["solution_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "solution_run_id",
            "candidate_version",
            "evidence_key",
            name="uq_evidence_records_run_key",
        ),
    )
    op.create_index(
        op.f("ix_evidence_records_is_deleted"), "evidence_records", ["is_deleted"], unique=False
    )
    op.create_index(
        "ix_evidence_records_source_version",
        "evidence_records",
        ["source_id", "source_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_records_workspace_id"), "evidence_records", ["workspace_id"], unique=False
    )
    op.create_table(
        "human_review_records",
        sa.Column("solution_run_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column("expected_decision_version", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("edits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence_changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["solution_run_id"], ["solution_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "solution_run_id", "expected_decision_version", name="uq_human_review_run_version"
        ),
    )
    op.create_index(
        op.f("ix_human_review_records_is_deleted"),
        "human_review_records",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_human_review_records_workspace_id"),
        "human_review_records",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "presentation_runs",
        sa.Column("solution_run_id", sa.UUID(), nullable=False),
        sa.Column("solution_version", sa.Integer(), nullable=False),
        sa.Column("style_profile_id", sa.UUID(), nullable=False),
        sa.Column("style_version", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "queued",
                "planning",
                "rendering",
                "validating",
                "ready",
                "needs_review",
                "failed",
                "stale",
                "blocked",
                name="presentation_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("trace_id", sa.String(length=128), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("audience", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("requested_outputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("locked_block_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("upstream_trust_version", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["solution_run_id"], ["solution_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["style_profile_id"], ["style_profiles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_presentation_runs_is_deleted"), "presentation_runs", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_presentation_runs_workspace_id"),
        "presentation_runs",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_presentation_solution_status",
        "presentation_runs",
        ["solution_run_id", "status"],
        unique=False,
    )
    op.create_table(
        "quality_attempt_records",
        sa.Column("solution_run_id", sa.UUID(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("candidate_version", sa.Integer(), nullable=False),
        sa.Column("failed_claim_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("verifier_version", sa.String(length=128), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["solution_run_id"], ["solution_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "solution_run_id", "candidate_version", "attempt", name="uq_quality_attempt_run_attempt"
        ),
    )
    op.create_index(
        op.f("ix_quality_attempt_records_is_deleted"),
        "quality_attempt_records",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quality_attempt_records_workspace_id"),
        "quality_attempt_records",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "retrieval_snapshot_records",
        sa.Column("solution_run_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("snapshot_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("permission_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding_version", sa.String(length=128), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["solution_run_id"], ["solution_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "solution_run_id", "version", name="uq_retrieval_snapshots_run_version"
        ),
    )
    op.create_index(
        op.f("ix_retrieval_snapshot_records_is_deleted"),
        "retrieval_snapshot_records",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_retrieval_snapshot_records_workspace_id"),
        "retrieval_snapshot_records",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_retrieval_snapshots_run",
        "retrieval_snapshot_records",
        ["solution_run_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "trust_decision_records",
        sa.Column("solution_run_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "pending",
                "release",
                "downgrade",
                "review",
                "block",
                name="trust_decision_action",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gate_policy_version", sa.String(length=128), nullable=False),
        sa.Column("threshold_version", sa.String(length=128), nullable=False),
        sa.Column("decided_by", sa.String(length=32), nullable=False),
        sa.Column("decision_details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["solution_run_id"], ["solution_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("solution_run_id", "version", name="uq_trust_decision_run_version"),
    )
    op.create_index(
        op.f("ix_trust_decision_records_is_deleted"),
        "trust_decision_records",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trust_decision_records_workspace_id"),
        "trust_decision_records",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_trust_decision_run_created",
        "trust_decision_records",
        ["solution_run_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "claim_evidence_links",
        sa.Column("solution_run_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column(
            "label",
            sa.Enum(
                "entailed",
                "contradicted",
                "insufficient",
                "invalid",
                name="claim_evidence_label",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("verifier_version", sa.String(length=128), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claim_records.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence_records.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["solution_run_id"], ["solution_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("claim_id", "evidence_id", name="uq_claim_evidence_link"),
    )
    op.create_index(
        op.f("ix_claim_evidence_links_is_deleted"),
        "claim_evidence_links",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_claim_evidence_links_workspace_id"),
        "claim_evidence_links",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "html_artifacts",
        sa.Column("presentation_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("html", sa.Text(), nullable=False),
        sa.Column("css", sa.Text(), nullable=False),
        sa.Column("assets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("render_report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provider_mode", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["presentation_id"], ["presentation_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("presentation_id", "version", name="uq_html_artifact_version"),
    )
    op.create_index(
        op.f("ix_html_artifacts_is_deleted"), "html_artifacts", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_html_artifacts_workspace_id"), "html_artifacts", ["workspace_id"], unique=False
    )
    op.create_table(
        "presentation_input_snapshots",
        sa.Column("presentation_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("snapshot_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["presentation_id"], ["presentation_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("presentation_id", "version", name="uq_presentation_snapshot_version"),
    )
    op.create_index(
        op.f("ix_presentation_input_snapshots_is_deleted"),
        "presentation_input_snapshots",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_presentation_input_snapshots_workspace_id"),
        "presentation_input_snapshots",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "export_artifacts",
        sa.Column("presentation_id", sa.UUID(), nullable=False),
        sa.Column("html_artifact_id", sa.UUID(), nullable=False),
        sa.Column("export_type", sa.String(length=16), nullable=False),
        sa.Column("object_key", sa.String(length=1000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "ready",
                "failed",
                name="export_artifact_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("provider_mode", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["html_artifact_id"], ["html_artifacts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["presentation_id"], ["presentation_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "presentation_id", "html_artifact_id", "export_type", name="uq_export_artifact"
        ),
    )
    op.create_index(
        op.f("ix_export_artifacts_is_deleted"), "export_artifacts", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_export_artifacts_workspace_id"), "export_artifacts", ["workspace_id"], unique=False
    )
    op.add_column(
        "solution_runs",
        sa.Column("stage", sa.String(length=64), server_default="queued", nullable=False),
    )
    op.add_column("solution_runs", sa.Column("trace_id", sa.String(length=128), nullable=True))
    op.execute("UPDATE solution_runs SET trace_id = 'legacy-' || id::text WHERE trace_id IS NULL")
    op.alter_column("solution_runs", "trace_id", nullable=False)
    op.add_column(
        "solution_runs", sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "solution_runs",
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "solution_runs",
        sa.Column("result_version", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("solution_runs", "result_version")
    op.drop_column("solution_runs", "attempt_count")
    op.drop_column("solution_runs", "deadline_at")
    op.drop_column("solution_runs", "trace_id")
    op.drop_column("solution_runs", "stage")
    op.drop_index(op.f("ix_export_artifacts_workspace_id"), table_name="export_artifacts")
    op.drop_index(op.f("ix_export_artifacts_is_deleted"), table_name="export_artifacts")
    op.drop_table("export_artifacts")
    op.drop_index(
        op.f("ix_presentation_input_snapshots_workspace_id"),
        table_name="presentation_input_snapshots",
    )
    op.drop_index(
        op.f("ix_presentation_input_snapshots_is_deleted"),
        table_name="presentation_input_snapshots",
    )
    op.drop_table("presentation_input_snapshots")
    op.drop_index(op.f("ix_html_artifacts_workspace_id"), table_name="html_artifacts")
    op.drop_index(op.f("ix_html_artifacts_is_deleted"), table_name="html_artifacts")
    op.drop_table("html_artifacts")
    op.drop_index(op.f("ix_claim_evidence_links_workspace_id"), table_name="claim_evidence_links")
    op.drop_index(op.f("ix_claim_evidence_links_is_deleted"), table_name="claim_evidence_links")
    op.drop_table("claim_evidence_links")
    op.drop_index("ix_trust_decision_run_created", table_name="trust_decision_records")
    op.drop_index(
        op.f("ix_trust_decision_records_workspace_id"), table_name="trust_decision_records"
    )
    op.drop_index(op.f("ix_trust_decision_records_is_deleted"), table_name="trust_decision_records")
    op.drop_table("trust_decision_records")
    op.drop_index("ix_retrieval_snapshots_run", table_name="retrieval_snapshot_records")
    op.drop_index(
        op.f("ix_retrieval_snapshot_records_workspace_id"), table_name="retrieval_snapshot_records"
    )
    op.drop_index(
        op.f("ix_retrieval_snapshot_records_is_deleted"), table_name="retrieval_snapshot_records"
    )
    op.drop_table("retrieval_snapshot_records")
    op.drop_index(
        op.f("ix_quality_attempt_records_workspace_id"), table_name="quality_attempt_records"
    )
    op.drop_index(
        op.f("ix_quality_attempt_records_is_deleted"), table_name="quality_attempt_records"
    )
    op.drop_table("quality_attempt_records")
    op.drop_index("ix_presentation_solution_status", table_name="presentation_runs")
    op.drop_index(op.f("ix_presentation_runs_workspace_id"), table_name="presentation_runs")
    op.drop_index(op.f("ix_presentation_runs_is_deleted"), table_name="presentation_runs")
    op.drop_table("presentation_runs")
    op.drop_index(op.f("ix_human_review_records_workspace_id"), table_name="human_review_records")
    op.drop_index(op.f("ix_human_review_records_is_deleted"), table_name="human_review_records")
    op.drop_table("human_review_records")
    op.drop_index(op.f("ix_evidence_records_workspace_id"), table_name="evidence_records")
    op.drop_index("ix_evidence_records_source_version", table_name="evidence_records")
    op.drop_index(op.f("ix_evidence_records_is_deleted"), table_name="evidence_records")
    op.drop_table("evidence_records")
    op.drop_index(op.f("ix_claim_records_workspace_id"), table_name="claim_records")
    op.drop_index("ix_claim_records_run_status", table_name="claim_records")
    op.drop_index(op.f("ix_claim_records_is_deleted"), table_name="claim_records")
    op.drop_table("claim_records")
    op.drop_index("ix_style_profiles_workspace_status", table_name="style_profiles")
    op.drop_index(op.f("ix_style_profiles_workspace_id"), table_name="style_profiles")
    op.drop_index(op.f("ix_style_profiles_is_deleted"), table_name="style_profiles")
    op.drop_table("style_profiles")
    op.drop_index(op.f("ix_reference_decks_workspace_id"), table_name="reference_decks")
    op.drop_index(op.f("ix_reference_decks_is_deleted"), table_name="reference_decks")
    op.drop_table("reference_decks")
    op.drop_index(op.f("ix_workflow_tasks_workspace_id"), table_name="workflow_tasks")
    op.drop_index(op.f("ix_workflow_tasks_is_deleted"), table_name="workflow_tasks")
    op.drop_index("ix_workflow_tasks_claim", table_name="workflow_tasks")
    op.drop_table("workflow_tasks")
    # ### end Alembic commands ###
