from enum import StrEnum
from typing import Any


class ErrorCode(StrEnum):
    AUTH_REQUIRED = "AUTH_REQUIRED"
    INVITE_CODE_INVALID = "INVITE_CODE_INVALID"
    FEISHU_AUTH_EXPIRED = "FEISHU_AUTH_EXPIRED"
    FEISHU_PERMISSION_DENIED = "FEISHU_PERMISSION_DENIED"
    SOURCE_NOT_FOUND = "SOURCE_NOT_FOUND"
    SOURCE_TYPE_UNSUPPORTED = "SOURCE_TYPE_UNSUPPORTED"
    SOURCE_TEMPORARILY_UNAVAILABLE = "SOURCE_TEMPORARILY_UNAVAILABLE"
    CONTENT_EMPTY = "CONTENT_EMPTY"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    IDEMPOTENCY_KEY_CONFLICT = "IDEMPOTENCY_KEY_CONFLICT"
    MODEL_TEMPORARILY_UNAVAILABLE = "MODEL_TEMPORARILY_UNAVAILABLE"
    AI_OUTPUT_INVALID = "AI_OUTPUT_INVALID"
    CLAIM_EXTRACTION_FAILED = "CLAIM_EXTRACTION_FAILED"
    EVIDENCE_LOCATION_INVALID = "EVIDENCE_LOCATION_INVALID"
    EVIDENCE_PERMISSION_REVOKED = "EVIDENCE_PERMISSION_REVOKED"
    EVIDENCE_VERSION_STALE = "EVIDENCE_VERSION_STALE"
    VERIFIER_UNAVAILABLE = "VERIFIER_UNAVAILABLE"
    TRUST_REVIEW_REQUIRED = "TRUST_REVIEW_REQUIRED"
    TRUST_GATE_BLOCKED = "TRUST_GATE_BLOCKED"
    PRESENTATION_UPSTREAM_NOT_RELEASED = "PRESENTATION_UPSTREAM_NOT_RELEASED"
    PRESENTATION_RENDER_FAILED = "PRESENTATION_RENDER_FAILED"
    REFERENCE_DECK_UNSAFE = "REFERENCE_DECK_UNSAFE"
    JOB_FAILED = "JOB_FAILED"
    RATE_LIMITED = "RATE_LIMITED"
    UNSAFE_EXTERNAL_URL = "UNSAFE_EXTERNAL_URL"
    INTELLIGENCE_ITEM_UNAVAILABLE = "INTELLIGENCE_ITEM_UNAVAILABLE"
    PROPOSAL_ALREADY_DECIDED = "PROPOSAL_ALREADY_DECIDED"
    TENDER_FILE_UNSAFE = "TENDER_FILE_UNSAFE"
    TENDER_FILE_TOO_LARGE = "TENDER_FILE_TOO_LARGE"
    TENDER_PARSE_TIMEOUT = "TENDER_PARSE_TIMEOUT"
    TENDER_PARSE_FAILED = "TENDER_PARSE_FAILED"
    TENDER_REQUIREMENT_EMPTY = "TENDER_REQUIREMENT_EMPTY"
    RESPONSE_EVIDENCE_INVALID = "RESPONSE_EVIDENCE_INVALID"
    RESPONSE_VERSION_CONFLICT = "RESPONSE_VERSION_CONFLICT"
    REHEARSAL_STATE_CONFLICT = "REHEARSAL_STATE_CONFLICT"
    MODEL_CONNECTION_UNAVAILABLE = "MODEL_CONNECTION_UNAVAILABLE"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class AppError(Exception):
    def __init__(
        self,
        code: ErrorCode,
        message: str,
        *,
        status_code: int = 400,
        retryable: bool = False,
        details: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.status_code = status_code
        self.retryable = retryable
        self.details = details or {}
